#!/usr/bin/env node
// Builds crates/cp-wasm for wasm32-unknown-unknown, optionally runs wasm-opt,
// copies the binary into packages/core/wasm/, and generates the inline
// (base64) module used by the `-compat` build. See ADR-0003.
import { execFileSync, spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
  copyFileSync,
  statSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const release = process.argv.includes("--release") || process.env.CI === "true";
const profile = release ? "wasm-release" : "dev";
const profileDir = release ? "wasm-release" : "debug";

const args = ["build", "-p", "cp-wasm", "--target", "wasm32-unknown-unknown", "--profile", profile];
console.log(`[build-wasm] cargo ${args.join(" ")}`);
execFileSync("cargo", args, { cwd: root, stdio: "inherit" });

const built = join(root, "target", "wasm32-unknown-unknown", profileDir, "cp_wasm.wasm");
const outDir = join(root, "packages", "core", "wasm");
mkdirSync(outDir, { recursive: true });
const out = join(outDir, "contactpatch.wasm");
copyFileSync(built, out);

// Optional size optimisation. Never changes semantics: no fast-math, no
// relaxed SIMD. Looks for a wasm-opt on the PATH, then the binaryen package.
let optimised = false;
const candidates = ["wasm-opt", join(root, "node_modules", ".bin", "wasm-opt")];
for (const bin of candidates) {
  const probe = spawnSync(bin, ["--version"], { stdio: "ignore" });
  if (probe.status === 0) {
    const r = spawnSync(bin, ["-Os", "--strip-debug", "--strip-producers", out, "-o", out], {
      stdio: "inherit",
    });
    optimised = r.status === 0;
    if (optimised) break;
  }
}

const bytes = readFileSync(out);
const genDir = join(root, "packages", "core", "src", "generated");
mkdirSync(genDir, { recursive: true });
const inline = `// Generated by scripts/build-wasm.mjs. Do not edit.\n// Inline copy of contactpatch.wasm for the compat build (works in any bundler).\nexport const wasmBase64 = "${bytes.toString("base64")}";\n`;
writeFileSync(join(genDir, "wasm-inline.ts"), inline);

const gz = gzipSync(bytes).length;
console.log(
  `[build-wasm] ${profile}: ${statSync(out).size} bytes (${gz} gzipped)${optimised ? ", wasm-opt applied" : ""} -> packages/core/wasm/contactpatch.wasm`,
);
if (release && gz > 200 * 1024) {
  console.error(`[build-wasm] gzipped size ${gz} exceeds the 200 KB budget`);
  process.exit(1);
}
if (!existsSync(out)) process.exit(1);
